on:
  workflow_dispatch: {}
jobs:
  flatpak-build:
    secrets: inherit
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
        flatpak:
          - name: handyfox
            id: io.github.pocketblue.handyfox
          - name: firefox-systemconfig
            id: org.mozilla.firefox.systemconfig
    uses: ./.github/workflows/helper-flatpak-builder.yml
    with:
      runner: ${{ matrix.runner}}
      name: ${{ matrix.flatpak.name }}
      id: ${{ matrix.flatpak.id }}
  push_repo:
    runs-on: ubuntu-latest
    needs: flatpak-build
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          echo '${{ secrets.private_gpg }}' | gpg --import
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: write metadata
        run: |
          mkdir ./deploy/repo
          ostree init --mode=archive-z2 --repo ./deploy/repo
          for dir in ./artifacts/* ; do
            mkdir -p $dir/refs/remotes $dir/refs/mirrors
            touch $dir/refs/remotes/.gitkeep $dir/refs/mirrors/.gitkeep
            ostree --repo=./deploy/repo pull-local $dir
          done
          flatpak build-update-repo --gpg-sign='${{ vars.gpg_email }}' ./deploy/repo
      - name: deploy to separate branch
        run: |
          TEMP_DIR=$(mktemp -d)
          git config --global --add safe.directory "$(pwd)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cp -a ./deploy/* $TEMP_DIR/
          git checkout --orphan storage-repo
          find . -maxdepth 1 -mindepth 1 -not -path './.git' -exec rm -rf {} +
          cp -a $TEMP_DIR/* .
          git add .
          git commit -m "Deploy flatpak repo"
          git push origin storage-repo --force
  publish:
    needs: push_repo
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
